// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMtP447qMsCRscPqL6kkxVzZvDi0bPLjM',
    appId: '1:963699063042:web:43c2767d220b1a1def2a1b',
    messagingSenderId: '963699063042',
    projectId: 'fyp-v1-b47cd',
    authDomain: 'fyp-v1-b47cd.firebaseapp.com',
    databaseURL: 'https://fyp-v1-b47cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-v1-b47cd.appspot.com',
    measurementId: 'G-L3B5F85W27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA3DOy9r6OeC_7djYMq3pdtgK1ceGb2is',
    appId: '1:963699063042:android:8d675ba88284ba62ef2a1b',
    messagingSenderId: '963699063042',
    projectId: 'fyp-v1-b47cd',
    databaseURL: 'https://fyp-v1-b47cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-v1-b47cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsT7H1aYi-T7SrQi2y4HXC-rWnHHtKsmI',
    appId: '1:963699063042:ios:4de4010e8456e2e9ef2a1b',
    messagingSenderId: '963699063042',
    projectId: 'fyp-v1-b47cd',
    databaseURL: 'https://fyp-v1-b47cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-v1-b47cd.appspot.com',
    iosClientId: '963699063042-03dbh8jk0ir0g248lnq3kneq8qd775e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.utifeederFlutter',
  );
}
